import asyncio
import json
import os
import re
import numpy as np
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple
from services import log_service
from services.base_service import SingletonService
from database.pg_pool import get_pooled_connection
from config import settings
from services.track_asset_stages import CATALOG_AUDIO_EXTENSIONS

def is_hidden_track(metadata: Optional[Dict]) -> bool:
    return (metadata or {}).get("visibility", "public") in ("unlisted", "private")


class CatalogDatabaseService(SingletonService):
    def __init__(self):
        if getattr(self, '_initialized', False):
            return
        self.metadata_dir = settings.METADATA_DIR
        self.audio_dir = settings.AUDIO_DIR
        self.artwork_dir = settings.ARTWORK_DIR
        self.tracks = {}
        self.hidden_ids = set()
        self.track_ids = []
        self._catalog_initialized = False
        self._artwork_cache = {}
        self._initialized = True
        self.vector_db_service = None
        self.broadcast_callback = None
        self._catalog_version = 0
        self._phrase_cache = {}
        self._reload_lock = asyncio.Lock()
        self._reload_in_progress = False
        self._pending_adds = {}
        self._pending_removes = set()
        self._initialize_database()

    def _get_connection(self):
        return get_pooled_connection(settings.CATALOG_DATABASE_URL)

    def _initialize_database(self):
        conn = self._get_connection()
        c = conn.cursor()

        c.execute('''CREATE TABLE IF NOT EXISTS tracks
                     (
                         rowid INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                         track_id TEXT UNIQUE NOT NULL,
                         metadata_json TEXT NOT NULL,
                         created_at TEXT,
                         title TEXT,
                         primary_artist TEXT,
                         primary_genre TEXT,
                         duration INTEGER,
                         instrumental INTEGER,
                         vocal_gender TEXT,
                         has_mp3 INTEGER DEFAULT 0,
                         has_wav INTEGER DEFAULT 0,
                         has_artwork INTEGER DEFAULT 0,
                         is_ai_generated INTEGER DEFAULT 1,
                         uploaded_by_user_id INTEGER DEFAULT NULL
                     )''')

        c.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_track_id ON tracks(track_id)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_created_at ON tracks(created_at DESC)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_primary_genre ON tracks(primary_genre)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_primary_artist ON tracks(primary_artist)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_uploaded_by_user_id ON tracks(uploaded_by_user_id)')

        conn.commit()
        conn.close()

        log_service.catalog("✓ Catalog database initialized (PostgreSQL)")

    async def initialize(self):
        if self._catalog_initialized:
            return
        tracks, track_ids, artwork_cache = await self._scan_catalog()
        self._swap_catalog(tracks, track_ids, artwork_cache)
        self._catalog_initialized = True

    def _swap_catalog(self, tracks: Dict[str, Dict], track_ids: List[str], artwork_cache: Dict[str, bool]):
        for track_id in self._pending_removes:
            tracks.pop(track_id, None)
            artwork_cache.pop(track_id, None)
        for track_id, (metadata, has_artwork) in self._pending_adds.items():
            if track_id not in self._pending_removes:
                tracks[track_id] = metadata
                artwork_cache[track_id] = has_artwork
        track_ids = [tid for tid in track_ids if tid in tracks]
        known = set(track_ids)
        track_ids.extend(tid for tid in tracks if tid not in known)
        track_ids.sort(key=lambda tid: tracks[tid].get("created_at", ""), reverse=True)
        self._pending_adds = {}
        self._pending_removes = set()
        self.tracks = tracks
        self.track_ids = track_ids
        self._artwork_cache = artwork_cache
        self.hidden_ids = {tid for tid, meta in tracks.items() if is_hidden_track(meta)}
        self._bump_version()

    def _bump_version(self):
        self._catalog_version += 1
        self._phrase_cache = {}

    def add_track_to_memory(self, track_id: str, metadata: Dict, has_artwork: Optional[bool] = None):
        self.tracks[track_id] = metadata
        if is_hidden_track(metadata):
            self.hidden_ids.add(track_id)
        else:
            self.hidden_ids.discard(track_id)
        if track_id not in self.track_ids:
            self.track_ids.insert(0, track_id)
        if has_artwork is not None:
            self._artwork_cache[track_id] = has_artwork
        if self._reload_in_progress:
            self._pending_removes.discard(track_id)
            self._pending_adds[track_id] = (metadata, bool(has_artwork))
        self._bump_version()

    def remove_track_from_memory(self, track_id: str):
        self.tracks.pop(track_id, None)
        self.hidden_ids.discard(track_id)
        if track_id in self.track_ids:
            self.track_ids.remove(track_id)
        self._artwork_cache.pop(track_id, None)
        if self._reload_in_progress:
            self._pending_adds.pop(track_id, None)
            self._pending_removes.add(track_id)
        self._bump_version()

    async def _scan_catalog(self):
        tracks: Dict[str, Dict] = {}
        track_ids: List[str] = []
        artwork_cache: Dict[str, bool] = {}

        log_service.catalog("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        log_service.catalog("Loading Catalog from JSON → PostgreSQL Database")

        if not self.metadata_dir.exists():
            log_service.warning(f"Metadata directory not found: {self.metadata_dir}")
            return tracks, track_ids, artwork_cache

        from services.suno_metadata_service import MusicMetadata
        metadata_service = MusicMetadata()

        json_files = await asyncio.to_thread(list, self.metadata_dir.glob("*.json"))

        existing_db_ids = set(await asyncio.to_thread(self._get_all_track_ids_from_db))
        json_file_ids = {f.stem for f in json_files}

        removed_ids = existing_db_ids - json_file_ids
        if removed_ids:
            log_service.catalog(f"Removing {len(removed_ids)} tracks no longer in JSON files...")
            await asyncio.to_thread(self._bulk_delete_tracks, list(removed_ids))

        master_wav_dir = settings.ENHANCED_WAV_DIR
        no_master_ids = []
        for tid in existing_db_ids - removed_ids:
            wav_path = master_wav_dir / f"{tid}.wav"
            if not await asyncio.to_thread(wav_path.exists):
                no_master_ids.append(tid)
        if no_master_ids:
            log_service.catalog(f"Removing {len(no_master_ids)} tracks without master WAV...")
            await asyncio.to_thread(self._bulk_delete_tracks, no_master_ids)

        semaphore = asyncio.Semaphore(50)
        added_count = 0
        updated_count = 0

        async def process_file(json_file):
            async with semaphore:
                try:
                    metadata = await metadata_service.load_metadata(json_file.name)
                    if not metadata:
                        return None

                    track_id = json_file.stem

                    audio_exists = False
                    for ext in CATALOG_AUDIO_EXTENSIONS:
                        audio_path = self.audio_dir / f"{track_id}{ext}"
                        if await asyncio.to_thread(audio_path.exists):
                            audio_exists = True
                            break

                    wav_path = master_wav_dir / f"{track_id}.wav"
                    art_path = self.artwork_dir / f"{track_id}.jpeg"

                    wav_exists, art_exists = await asyncio.gather(
                        asyncio.to_thread(wav_path.exists),
                        asyncio.to_thread(art_path.exists)
                    )

                    if wav_exists:
                        metadata['id'] = track_id
                        is_new = await asyncio.to_thread(self._upsert_track_to_db, track_id, metadata, audio_exists,
                                                         wav_exists, art_exists)
                        return (track_id, metadata, is_new, art_exists)
                except Exception as e:
                    log_service.error(f"Error processing {json_file.name}: {e}")
                return None

        results = await asyncio.gather(*[process_file(f) for f in json_files])

        for res in results:
            if res:
                tid, meta, is_new, art_exists = res
                tracks[tid] = meta
                artwork_cache[tid] = art_exists
                track_ids.append(tid)
                if is_new:
                    added_count += 1
                else:
                    updated_count += 1

        track_ids.sort(key=lambda tid: tracks[tid].get("created_at", ""), reverse=True)

        log_service.catalog(
            f"📊 Sync complete: {len(tracks)} total | +{added_count} new | ~{updated_count} updated | -{len(removed_ids)} removed")
        log_service.catalog("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        return tracks, track_ids, artwork_cache

    def _get_all_track_ids_from_db(self) -> List[str]:
        conn = self._get_connection()
        c = conn.cursor()
        c.execute("SELECT track_id FROM tracks")
        ids = [row[0] for row in c.fetchall()]
        conn.close()
        return ids

    def _bulk_delete_tracks(self, track_ids: List[str]):
        conn = self._get_connection()
        c = conn.cursor()
        c.executemany("DELETE FROM tracks WHERE track_id = %s", [(tid,) for tid in track_ids])
        conn.commit()
        conn.close()

    def _delete_track_from_db(self, track_id: str):
        conn = self._get_connection()
        c = conn.cursor()
        c.execute("DELETE FROM tracks WHERE track_id = %s", (track_id,))
        conn.commit()
        conn.close()

    def _upsert_track_to_db(self, track_id: str, metadata: Dict, has_mp3: bool, has_wav: bool,
                            has_artwork: bool) -> bool:
        params = metadata.get("generation_params", {}) or {}
        derived = metadata.get("derived_tags", {}) or {}
        info = metadata.get("track_info", {}) or {}

        title = (params.get("title") or "").strip()
        artist = (params.get("artist_name") or "").strip()
        genre = (derived.get("primary_genre") or "").strip()
        vocal_gender = (params.get("vocal_gender") or "").strip()

        is_ai_generated = 1 if metadata.get("is_ai_generated", True) else 0
        uploaded_by_user_id = metadata.get("uploaded_by_user_id")

        conn = self._get_connection()
        c = conn.cursor()
        c.execute('''INSERT INTO tracks (metadata_json, created_at, title, primary_artist, primary_genre,
                                         duration, instrumental, vocal_gender, has_mp3, has_wav, has_artwork,
                                         is_ai_generated, uploaded_by_user_id, track_id)
                     VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                     ON CONFLICT (track_id) DO UPDATE
                     SET metadata_json = EXCLUDED.metadata_json,
                         created_at = EXCLUDED.created_at,
                         title = EXCLUDED.title,
                         primary_artist = EXCLUDED.primary_artist,
                         primary_genre = EXCLUDED.primary_genre,
                         duration = EXCLUDED.duration,
                         instrumental = EXCLUDED.instrumental,
                         vocal_gender = EXCLUDED.vocal_gender,
                         has_mp3 = EXCLUDED.has_mp3,
                         has_wav = EXCLUDED.has_wav,
                         has_artwork = EXCLUDED.has_artwork,
                         is_ai_generated = EXCLUDED.is_ai_generated,
                         uploaded_by_user_id = EXCLUDED.uploaded_by_user_id
                     RETURNING (xmax = 0)''',
                  (json.dumps(metadata), metadata.get("created_at", ""), title,
                   artist, genre, info.get("duration", 0),
                   1 if params.get("instrumental") else 0, vocal_gender,
                   int(has_mp3), int(has_wav), int(has_artwork),
                   is_ai_generated, uploaded_by_user_id, track_id))
        inserted = c.fetchone()[0]

        conn.commit()
        conn.close()
        return inserted

    def compute_track_flags(self, track_id: str) -> Tuple[bool, bool, bool]:
        has_mp3 = any((self.audio_dir / f"{track_id}{ext}").exists() for ext in CATALOG_AUDIO_EXTENSIONS)
        has_wav = (settings.ENHANCED_WAV_DIR / f"{track_id}.wav").exists()
        has_artwork = (self.artwork_dir / f"{track_id}.jpeg").exists()
        return has_mp3, has_wav, has_artwork

    def get_track_db_state(self, track_id: str) -> Optional[Dict[str, Any]]:
        conn = self._get_connection()
        try:
            c = conn.cursor()
            c.execute("SELECT rowid, has_mp3, has_wav, has_artwork FROM tracks WHERE track_id = %s", (track_id,))
            row = c.fetchone()
        finally:
            conn.close()
        if not row:
            return None
        return {"rowid": row[0], "has_mp3": bool(row[1]), "has_wav": bool(row[2]), "has_artwork": bool(row[3])}

    def update_track_flags(self, track_id: str, has_mp3: bool, has_wav: bool, has_artwork: bool) -> bool:
        conn = self._get_connection()
        try:
            c = conn.cursor()
            c.execute("UPDATE tracks SET has_mp3 = %s, has_wav = %s, has_artwork = %s WHERE track_id = %s",
                      (int(has_mp3), int(has_wav), int(has_artwork), track_id))
            updated = c.rowcount > 0
            conn.commit()
        finally:
            conn.close()
        if track_id in self.tracks:
            self._artwork_cache[track_id] = has_artwork
        return updated

    def refresh_track_flags(self, track_id: str) -> Tuple[bool, bool, bool]:
        flags = self.compute_track_flags(track_id)
        self.update_track_flags(track_id, *flags)
        return flags

    def write_track_metadata(self, track_id: str, metadata: Dict) -> Tuple[bool, bool, bool]:
        metadata_path = self.metadata_dir / f"{track_id}.json"
        temp_path = metadata_path.with_name(f"{track_id}.json.tmp")
        temp_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
        os.replace(temp_path, metadata_path)
        flags = self.compute_track_flags(track_id)
        self._upsert_track_to_db(track_id, metadata, *flags)
        return flags

    def get_track(self, track_id: str) -> Optional[Dict]:
        return self.tracks.get(track_id)

    def get_all_tracks(self, skip: int = 0, limit: int = 100, sort_by: str = "created_at", order: str = "desc",
                       genre: Optional[str] = None, banned_ids: Optional[set] = None) -> tuple:
        ids = self.track_ids

        if genre:
            ids = [tid for tid in ids if
                   (self.tracks[tid].get("derived_tags", {}).get("primary_genre") or "").lower() == genre.lower()]

        if banned_ids or self.hidden_ids:
            excluded = (banned_ids or set()) | self.hidden_ids
            ids = [tid for tid in ids if tid not in excluded]

        filtered_total = len(ids)

        reverse = (order == "desc")
        if sort_by == "title":
            ids = sorted(ids, key=lambda tid: (self.tracks[tid].get("generation_params", {}).get("title") or "").lower(),
                         reverse=reverse)
        elif sort_by == "artist_name":
            ids = sorted(ids,
                         key=lambda tid: (self.tracks[tid].get("generation_params", {}).get("artist_name") or "").lower(),
                         reverse=reverse)
        elif sort_by == "genre":
            ids = sorted(ids,
                         key=lambda tid: (self.tracks[tid].get("derived_tags", {}).get("primary_genre") or "zzz").lower(),
                         reverse=reverse)
        elif sort_by != "created_at":
            ids = sorted(ids, key=lambda tid: self.tracks[tid].get("created_at", ""), reverse=reverse)

        return [self.tracks[tid] for tid in ids[skip:skip + limit]], filtered_total

    def has_artwork(self, track_id: str) -> bool:
        if track_id in self._artwork_cache:
            return self._artwork_cache[track_id]
        exists = (self.artwork_dir / f"{track_id}.jpeg").exists()
        if track_id in self.tracks:
            self._artwork_cache[track_id] = exists
        return exists

    def update_track_artwork_status(self, track_id: str, has_artwork: bool) -> bool:
        conn = self._get_connection()
        c = conn.cursor()

        try:
            c.execute('''UPDATE tracks SET has_artwork = %s WHERE track_id = %s''',
                      (int(has_artwork), track_id))
            conn.commit()

            self._artwork_cache[track_id] = has_artwork

            log_service.info(f"[Catalog] Updated artwork status for {track_id}: {has_artwork}")
            return True
        except Exception as e:
            log_service.error(f"[Catalog] Failed to update artwork status: {e}")
            return False
        finally:
            conn.close()

    def set_vector_services(self, vector_db_service=None, broadcast_callback=None):
        self.vector_db_service = vector_db_service
        self.broadcast_callback = broadcast_callback

    async def reload_catalog(self):
        async with self._reload_lock:
            old_ids = set(self.tracks)
            self._reload_in_progress = True
            try:
                tracks, track_ids, artwork_cache = await self._scan_catalog()
                self._swap_catalog(tracks, track_ids, artwork_cache)
                self._catalog_initialized = True
            finally:
                self._reload_in_progress = False
                self._pending_adds = {}
                self._pending_removes = set()
            new_track_count = len(set(self.tracks) - old_ids)

            if new_track_count > 0 and self.vector_db_service:
                await asyncio.to_thread(
                    self.vector_db_service.rebuild_indexes,
                    self
                )
                log_service.success(
                    f"✅ Catalog vector indexes rebuilt immediately (+{new_track_count} new tracks)"
                )

                if self.broadcast_callback:
                    await self.broadcast_callback("track", "batch_reload", {
                        "new_tracks_count": new_track_count,
                        "total_tracks": len(self.tracks)
                    })

            return new_track_count

    def get_all_genres(self) -> List[Dict]:
        cached = getattr(self, "_genres_cache", None)
        if cached is not None and cached[0] == self._catalog_version:
            return cached[1]
        version = self._catalog_version
        genres = self._count_genres()
        self._genres_cache = (version, genres)
        return genres

    def _count_genres(self) -> List[Dict]:
        counts = Counter()
        sub_genres = {}
        for t in self.tracks.values():
            d = t.get("derived_tags", {})
            pg = d.get("primary_genre")
            if pg:
                counts[pg] += 1
                if pg not in sub_genres:
                    sub_genres[pg] = set()
                sub_genres[pg].update(d.get("secondary_genres", []))

        return sorted([{"genre": g, "count": c, "sub_genres": sorted(list(sub_genres[g]))} for g, c in counts.items()],
                      key=lambda x: x["count"], reverse=True)

    def get_audio_path(self, track_id: str) -> Optional[Path]:
        return self.audio_dir / f"{track_id}.mp3" if track_id in self.tracks else None

    def get_artwork_path(self, track_id: str) -> Optional[Path]:
        return self.artwork_dir / f"{track_id}.jpeg" if self.has_artwork(track_id) else None

    def get_repeated_titles(self, min_occurrences: int = 2) -> List[str]:
        counts = Counter(
            (self.tracks[tid].get("generation_params", {}).get("title") or "").strip().lower()
            for tid in self.tracks if self.tracks[tid].get("generation_params", {}).get("title")
        )
        return [t for t, c in counts.most_common() if c >= min_occurrences]

    def get_repeated_artists(self) -> List[str]:
        counts = Counter(
            (self.tracks[tid].get("generation_params", {}).get("artist_name") or "").strip().lower()
            for tid in self.tracks if self.tracks[tid].get("generation_params", {}).get("artist_name")
        )
        if not counts:
            return []
        threshold = np.percentile(list(counts.values()), 85)
        return [a for a, c in counts.most_common() if c > threshold and c > 1]

    def get_repeated_phrases(self, min_occurrences: int = 2, top_n: int = 20) -> List[str]:
        cache_key = (self._catalog_version, len(self.tracks), min_occurrences, top_n)
        cached = self._phrase_cache.get(cache_key)
        if cached is not None:
            return list(cached)
        phrases = self._compute_repeated_phrases(min_occurrences, top_n)
        self._phrase_cache[cache_key] = phrases
        return list(phrases)

    def _compute_repeated_phrases(self, min_occurrences: int, top_n: int) -> List[str]:
        phrase_counts = Counter()
        for track in list(self.tracks.values()):
            prompt = track.get("generation_params", {}).get("prompt", "")
            if not prompt:
                continue
            words = re.sub(r'\[.*?]|\(.*?\)', '', prompt).lower().split()
            for n in range(4, 7):
                for i in range(len(words) - n + 1):
                    p = ' '.join(words[i:i + n])
                    if len(p) > 15:
                        phrase_counts[p] += 1
        return [p for p, c in phrase_counts.most_common(top_n) if c >= min_occurrences]

    def get_cycled_phrases(self, cycle_index: int = 0, phrases_per_cycle: int = 5, top_n: int = 20) -> List[str]:
        phrases = self.get_repeated_phrases(min_occurrences=2, top_n=top_n)
        if not phrases:
            return []
        idx = (cycle_index * phrases_per_cycle) % len(phrases)
        return (phrases + phrases)[idx: idx + phrases_per_cycle]

    async def get_tracks_by_artist(self, artist_name: str) -> Dict[str, Any]:
        artist_lower = (artist_name or "").strip().lower()

        matching_tracks = []
        for tid in self.tracks:
            track = self.tracks[tid]
            track_artist = (track.get("generation_params", {}).get("artist_name") or "").strip().lower()
            inspired_artist = (track.get("derived_tags", {}).get("inspired_artist") or "").strip().lower()

            if track_artist == artist_lower or inspired_artist == artist_lower:
                matching_tracks.append(track)

        if not matching_tracks:
            return {
                "artist": artist_name,
                "track_count": 0,
                "message": f"No existing tracks found for {artist_name}. This is a NEW artist for your catalog!"
            }

        unique_tracks = {}
        seen_titles = set()

        for track in matching_tracks:
            title = (track.get("generation_params", {}).get("title") or "Untitled").strip()
            title_lower = title.lower()

            if title_lower in seen_titles:
                continue

            theme = track.get("derived_tags", {}).get("lyrical_interpretation", "")

            if title and theme:
                unique_tracks[title] = theme
                seen_titles.add(title_lower)

        existing_tracks = [
            {"title": title, "theme": theme}
            for title, theme in list(unique_tracks.items())[:15]
        ]

        result = {
            "artist": artist_name,
            "track_count": len(matching_tracks),
            "unique_track_count": len(unique_tracks),
            "existing_tracks": existing_tracks,
            "advice": f"You have {len(unique_tracks)} unique tracks for {artist_name}. Avoid repeating these titles and themes - create something FRESH with different subject matter."
        }

        try:
            log_service.catalog(f"[Catalog Tool] Returning data for '{artist_name}':")
            log_service.catalog(f"  - {len(matching_tracks)} total tracks ({len(unique_tracks)} unique)")
        except Exception as e:
            log_service.warning(f"[Catalog Tool] Log error: {e}")

        return result

    def get_stats(self, genre: Optional[str] = None) -> Dict:
        total, duration, inst, vocal = 0, 0, 0, 0
        for tid, t in self.tracks.items():
            if genre:
                track_genre = (t.get("derived_tags", {}).get("primary_genre") or "").lower()
                if track_genre != genre.lower():
                    continue
            total += 1
            duration += t.get("track_info", {}).get("duration", 0)
            if t.get("generation_params", {}).get("instrumental"):
                inst += 1
            else:
                vocal += 1
        return {
            "total_tracks": total, "total_duration_ms": duration,
            "total_duration_formatted": self._format_duration(duration),
            "instrumental_count": inst, "vocal_count": vocal
        }

    def _format_duration(self, ms: int) -> str:
        m, s = divmod(ms // 1000, 60)
        h, m = divmod(m, 60)
        return f"{h}h {m}m" if h else f"{m}m {s}s"