import json
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List

from config.settings import settings
from database.pg_pool import get_pooled_connection
from services.semantic_source import Category, SemanticVectorDatabaseService, field_text, make_prompt_cache


class ListenerRequestStore:
    table = "listener_requests"

    def _get_connection(self):
        return get_pooled_connection(settings.USER_CONTENT_DATABASE_URL)

    def initialize(self) -> None:
        conn = self._get_connection()
        try:
            c = conn.cursor()
            c.execute(f'''CREATE TABLE IF NOT EXISTS {self.table} (
                              rowid INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                              request_id TEXT UNIQUE NOT NULL,
                              region_key TEXT NOT NULL,
                              intent TEXT NOT NULL,
                              asked_at TIMESTAMPTZ NOT NULL,
                              metadata_json TEXT NOT NULL
                          )''')
            c.execute(f"CREATE INDEX IF NOT EXISTS idx_{self.table}_region ON {self.table}(region_key, asked_at DESC)")
            conn.commit()
        finally:
            conn.close()

    def add(self, meta: Dict[str, Any]) -> int:
        conn = self._get_connection()
        try:
            c = conn.cursor()
            c.execute(f"INSERT INTO {self.table} (request_id, region_key, intent, asked_at, metadata_json) "
                      f"VALUES (%s, %s, %s, %s, %s) RETURNING rowid",
                      (meta["request_id"], meta["region_key"], meta["intent"], meta["asked_at"], json.dumps(meta)))
            rowid = c.fetchone()[0]
            conn.commit()
            return rowid
        finally:
            conn.close()

    def prune(self, keep_days: int) -> int:
        conn = self._get_connection()
        try:
            c = conn.cursor()
            c.execute(f"DELETE FROM {self.table} WHERE asked_at < %s",
                      (datetime.now(timezone.utc) - timedelta(days=keep_days),))
            removed = c.rowcount
            conn.commit()
            return removed
        finally:
            conn.close()


class ListenerRequestVectorDatabaseService(SemanticVectorDatabaseService):
    category_specs = (
        Category("request_text", 0.30, field_text("text"), "What the listener asked, in their words"),
        Category("request_topic", 0.25, field_text("topic"), "The subject of the ask (jazz gigs, cafes, a news topic)"),
        Category("request_answers", 0.20, field_text("answers"), "What the station answered with (names of places, gigs, stories)"),
        Category("request_intent", 0.10, field_text("intent"), "Which kind of knowledge was asked for (events, places, news...)"),
        Category("request_area", 0.10, field_text("area"), "Where the listener was, suburb or street"),
        Category("request_daypart", 0.05, lambda item: f"{item.get('weekday') or ''} {item.get('daypart') or ''}".strip(),
                 "When they asked: day and time of day"),
    )
    encoder_name = settings.PULSE_ENCODER
    embedding_dim = settings.PULSE_ENCODER_DIM
    log_channel = "system"
    service_label = "Listener requests"
    display_name = "Listener Requests"
    tables_setting_name = ""
    index_dir_setting_name = "EMBEDDINGS_DIR"
    index_file_prefix = "listener_requests"
    source_table = "listener_requests"
    source_id_column = "request_id"
    source_label = "listener requests"
    source_db_label = "user_content"
    item_noun = "requests"
    single_item_noun = "request"

    def add_request(self, meta: Dict[str, Any], rowid: int) -> None:
        self._add_single_item(meta)
        self._rowid_cache[rowid] = meta["request_id"]
        self._metadata_cache[rowid] = meta
        self.dirty = True

    def rows(self, region_key: str, since: datetime) -> List[tuple]:
        found = []
        for rowid, meta in list(self._metadata_cache.items()):
            if meta.get("region_key") != region_key:
                continue
            try:
                asked = datetime.fromisoformat(meta.get("asked_at"))
            except (TypeError, ValueError):
                continue
            if asked >= since:
                found.append((rowid, meta))
        return found


ListenerRequestPromptCache = make_prompt_cache(
    ListenerRequestVectorDatabaseService, "listener_request_query_intent_cache",
    "what listeners in a city have been asking the station about",
    "- 'food': request_topic and request_answers high.\n"
    "- 'what are people asking about gigs': request_intent and request_topic high.\n"
    "- 'around K Road': request_area high.")


def daypart(moment: datetime) -> str:
    hour = moment.hour
    if 5 <= hour < 12:
        return "morning"
    if 12 <= hour < 17:
        return "afternoon"
    if 17 <= hour < 22:
        return "evening"
    return "late night"
