import asyncio
import json
import os
import time
import aiofiles
from typing import Dict, List, Optional, Union, Callable
from datetime import datetime, timezone
from services import log_service
from services.base_service import SingletonService
from database.pg_pool import get_pooled_connection
from config import settings
from pathlib import Path
from sqlalchemy import select
from database.models import User

PRIVATE_SHOUTOUT_KEYS = ("latitude", "longitude", "lat", "lon", "lng", "coordinates", "distance_km")
KIND_SHOUTOUT = "shoutout"
KIND_REPLY = "reply"
KIND_REVIEW = "review"
KINDS = (KIND_SHOUTOUT, KIND_REPLY, KIND_REVIEW)


def kind_of(item: Optional[Dict]) -> str:
    if not isinstance(item, dict):
        return KIND_SHOUTOUT
    kind = item.get("content_type")
    if kind in KINDS:
        return kind
    return KIND_REPLY if item.get("parent_id") else KIND_SHOUTOUT


def track_ref(track: Optional[Dict]) -> Optional[Dict]:
    if not track or not track.get("id"):
        return None
    params = track.get("generation_params") or {}
    artists = log_service.track_artists(track)
    genre = (track.get("derived_tags") or {}).get("primary_genre") or params.get("style")
    return {"id": str(track["id"]), "title": params.get("title") or track.get("title") or str(track["id"]),
            "artist": artists[0] if artists else None, "genre": genre}


def sting_file(mp3_path) -> str:
    base, _ext = os.path.splitext(str(mp3_path))
    return f"{base}_sting.mp3"


def coarse_location(location: Optional[str]) -> Optional[str]:
    if not location or not isinstance(location, str):
        return None
    parts = [p.strip() for p in location.split(",") if p.strip()]
    if not parts:
        return None
    return ", ".join(parts[-2:])


def public_shoutout(item: Optional[Dict]) -> Optional[Dict]:
    if not isinstance(item, dict):
        return item
    public = {k: v for k, v in item.items() if k not in PRIVATE_SHOUTOUT_KEYS}
    user_data = item.get("user_data")
    if isinstance(user_data, dict):
        safe_user_data = {k: v for k, v in user_data.items() if k not in PRIVATE_SHOUTOUT_KEYS}
        if "location" in safe_user_data:
            safe_user_data["location"] = coarse_location(safe_user_data.get("location"))
        public["user_data"] = safe_user_data
    if "location" in public and isinstance(public.get("location"), str):
        public["location"] = coarse_location(public["location"])
    for key in ("transcription_metadata", "metadata"):
        meta = public.get(key)
        if isinstance(meta, dict) and isinstance(meta.get("where"), dict):
            where = meta["where"]
            public[key] = {**meta, "where": {"label": where.get("label"), "scope": where.get("scope")}}
    return public


def public_shoutouts(items: Optional[List[Dict]]) -> List[Dict]:
    return [public_shoutout(item) for item in (items or []) if item]  # type: ignore

class UserContentDatabaseService(SingletonService):
    def __init__(self):
        if getattr(self, '_initialized', False):
            return
        self.users_dir = settings.USERS_DIR

        self.shoutouts = {}
        self.shoutout_ids = []
        self.children: Dict[str, set] = {}
        self._service_initialized = False
        self._initialized = True

        self._initialize_database()

    def _get_connection(self):
        return get_pooled_connection(settings.USER_CONTENT_DATABASE_URL)

    def _initialize_database(self):
        conn = self._get_connection()
        c = conn.cursor()

        c.execute('''CREATE TABLE IF NOT EXISTS shoutouts
                     (
                         rowid INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                         content_id TEXT UNIQUE NOT NULL,
                         user_id INTEGER,
                         metadata_json TEXT NOT NULL,
                         created_at TEXT,
                         transcription TEXT,
                         category TEXT,
                         duration REAL,
                         username TEXT,
                         location TEXT,
                         has_mp3 INTEGER DEFAULT 0,
                         parent_id TEXT DEFAULT NULL,
                         reply_count INTEGER DEFAULT 0
                     )''')

        c.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_content_id ON shoutouts(content_id)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_created_at ON shoutouts(created_at DESC)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_user_id ON shoutouts(user_id)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_category ON shoutouts(category)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_parent_id ON shoutouts(parent_id)')
        c.execute("ALTER TABLE shoutouts ADD COLUMN IF NOT EXISTS kind TEXT DEFAULT 'shoutout'")
        c.execute('ALTER TABLE shoutouts ADD COLUMN IF NOT EXISTS track_id TEXT DEFAULT NULL')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_kind ON shoutouts(kind)')
        c.execute('CREATE INDEX IF NOT EXISTS idx_shoutouts_track_id ON shoutouts(track_id)')

        conn.commit()
        conn.close()

        log_service.user_content("✓ User Content database table initialized (PostgreSQL)")

    async def initialize(self):
        if self._service_initialized:
            return
        log_service.detail("Loading Shoutouts from JSON → PostgreSQL Database", "user_content")

        if not self.users_dir.exists():
            log_service.warning(f"Users directory not found: {self.users_dir}")
            self._service_initialized = True
            return

        json_files = []

        try:
            for user_dir in self.users_dir.iterdir():
                if not user_dir.is_dir():
                    continue

                try:
                    user_id = int(user_dir.name)
                    shoutouts_dir = settings.get_user_shoutouts_dir(user_id)
                except ValueError:
                    continue

                if shoutouts_dir.exists() and shoutouts_dir.is_dir():
                    user_json_files = list(shoutouts_dir.glob("*.json"))
                    json_files.extend(user_json_files)
        except Exception as e:
            log_service.error(f"Error scanning user directories: {e}")

        existing_db_ids = set(await asyncio.to_thread(self._get_all_shoutout_ids_from_db))

        file_id_map = {}
        for f in json_files:
            try:
                user_id = f.parent.parent.name
                timestamp = f.stem
                shoutout_id = f"{user_id}_{timestamp}"
                file_id_map[shoutout_id] = f
            except Exception:
                continue

        json_file_ids = set(file_id_map.keys())
        removed_ids = existing_db_ids - json_file_ids

        if removed_ids:
            log_service.user_content(f"Removing {len(removed_ids)} shoutouts no longer on disk...")
            await asyncio.to_thread(self._bulk_delete_shoutouts, list(removed_ids))

        semaphore = asyncio.Semaphore(50)
        added_count = 0
        updated_count = 0

        async def process_file(shoutout_id, json_path):
            async with semaphore:
                try:
                    async with aiofiles.open(json_path, 'r', encoding='utf-8') as f:
                        content = await f.read()
                        metadata = json.loads(content)

                    audio_path = json_path.with_suffix('.mp3')
                    has_mp3 = audio_path.exists()

                    if has_mp3 or metadata.get('text_only'):
                        metadata['id'] = shoutout_id
                        user_id_from_path = json_path.parent.parent.name

                        is_new = await asyncio.to_thread(
                            self._upsert_shoutout_to_db,
                            shoutout_id,
                            int(user_id_from_path),
                            metadata,
                            has_mp3
                        )
                        return shoutout_id, metadata, is_new
                except Exception as e:
                    log_service.error(f"Error processing {json_path.name}: {e}")
                return None

        tasks = [process_file(sid, fpath) for sid, fpath in file_id_map.items()]
        results = await asyncio.gather(*tasks)

        for res in results:
            if res:
                sid, meta, is_new = res
                self.shoutouts[sid] = meta
                if sid not in self.shoutout_ids:
                    self.shoutout_ids.append(sid)
                if is_new:
                    added_count += 1
                else:
                    updated_count += 1

        self.shoutout_ids.sort(key=lambda sid: self.shoutouts[sid].get("timestamp", ""), reverse=True)
        self.children = {}
        for sid, meta in self.shoutouts.items():
            if meta.get("parent_id"):
                self.children.setdefault(meta["parent_id"], set()).add(sid)

        log_service.user_content(
            f"Shoutouts synced: {len(self.shoutouts)} shoutouts | +{added_count} new | ~{updated_count} updated | -{len(removed_ids)} removed")
        self._service_initialized = True

    async def save_audio_file(self, user_id: Union[int, str], timestamp: str, audio_bytes: bytes) -> Optional[Path]:
        try:
            uploads_dir = settings.get_user_uploads_dir(int(user_id))
            webm_path = uploads_dir / f"{timestamp}.webm"

            async with aiofiles.open(webm_path, 'wb') as f:
                await f.write(audio_bytes)
            return webm_path
        except Exception as e:
            log_service.error(f"Failed to save audio file: {e}")
            return None

    async def save_metadata_file(self, user_id: Union[int, str], timestamp: str, metadata: Dict) -> Optional[Path]:
        try:
            uploads_dir = settings.get_user_uploads_dir(int(user_id))
            json_path = uploads_dir / f"{timestamp}.json"

            async with aiofiles.open(json_path, 'w', encoding='utf-8') as f:
                await f.write(json.dumps(metadata, indent=2, ensure_ascii=False))
            return json_path
        except Exception as e:
            log_service.error(f"Failed to save metadata file: {e}")
            return None

    def remember_shoutout(self, shoutout_id: str, metadata: Dict):
        previous = self.shoutouts.get(shoutout_id)
        if previous and previous.get("parent_id"):
            self.children.get(previous["parent_id"], set()).discard(shoutout_id)
        self.shoutouts[shoutout_id] = metadata
        if metadata.get("parent_id"):
            self.children.setdefault(metadata["parent_id"], set()).add(shoutout_id)
        if shoutout_id not in self.shoutout_ids:
            self.shoutout_ids.insert(0, shoutout_id)
            self.shoutout_ids.sort(key=lambda sid: self.shoutouts[sid].get("timestamp", ""), reverse=True)

    def forget_shoutout(self, shoutout_id: str):
        from service_registry import services
        if services.user_content_vector_db_service is not None:
            services.user_content_vector_db_service.remove(shoutout_id)
        previous = self.shoutouts.pop(shoutout_id, None)
        if previous and previous.get("parent_id"):
            self.children.get(previous["parent_id"], set()).discard(shoutout_id)
        if shoutout_id in self.shoutout_ids:
            self.shoutout_ids.remove(shoutout_id)

    @staticmethod
    def _remove_files(paths: List[Optional[Path]]):
        for path in paths:
            try:
                if path is not None and path.exists():
                    path.unlink()
            except Exception as e:
                log_service.warning(f"Failed to remove {path}: {e}")

    def parent_problem(self, parent_id: Optional[str]) -> Optional[str]:
        parent = self.shoutouts.get(parent_id) if parent_id else None
        if parent is None:
            return "That shoutout no longer exists"
        if kind_of(parent) != KIND_SHOUTOUT:
            return "Replies can only go to a shoutout, not to a reply or a review"
        return None

    def _llm_context(self, kind: str, parent_id: Optional[str], track: Optional[Dict]) -> Dict:
        if kind == KIND_REPLY and parent_id in self.shoutouts:
            parent = self.shoutouts[parent_id]
            return {"replying_to": {"from": (parent.get("user_data") or {}).get("username"),
                                    "message": parent.get("full_transcription", "")}}
        if kind == KIND_REVIEW and track:
            return {"track": {k: track.get(k) for k in ("title", "artist", "genre") if track.get(k)}}
        return {}

    def _new_stamp(self, user_id: int) -> str:
        stamp = int(time.time())
        shoutouts_dir = settings.get_user_shoutouts_dir(user_id)
        while (shoutouts_dir / f"{stamp}.json").exists() or f"{user_id}_{stamp}" in self.shoutouts:
            stamp += 1
        return str(stamp)

    async def create_voice_item(self, user_id: int, kind: str, webm_path: Optional[Path], enhancement_service,
                                ai_service, vector_db_service=None, broadcast_callback: Optional[Callable] = None,
                                parent_id: Optional[str] = None, track: Optional[Dict] = None) -> Optional[Dict]:
        target_mp3_path = None
        target_json_path = None
        registered = False
        try:
            if kind == KIND_REPLY and self.parent_problem(parent_id):
                log_service.error(f"Reply refused for {parent_id}: {self.parent_problem(parent_id)}")
                return None
            if not webm_path or not webm_path.exists() or not webm_path.with_suffix(".json").exists():
                log_service.error(f"No recording to save as a {kind} for user {user_id}")
                return None

            timestamp = webm_path.stem
            shoutouts_dir = settings.get_user_shoutouts_dir(user_id)
            target_mp3_path = shoutouts_dir / f"{timestamp}.mp3"
            target_json_path = shoutouts_dir / f"{timestamp}.json"

            enhanced = await enhancement_service.enhance_audio(
                str(webm_path), str(target_mp3_path), kind, str(webm_path.with_suffix(".json")),
                str(target_json_path), ai_service, context=self._llm_context(kind, parent_id, track)
            )
            if not enhanced or not target_json_path.exists() or not target_mp3_path.exists():
                log_service.error(f"{kind} processing produced no audio/transcript for {user_id}_{timestamp}")
                await asyncio.to_thread(self._remove_files, [target_mp3_path, target_json_path,
                                                             Path(sting_file(target_mp3_path))])
                return None

            async with aiofiles.open(target_json_path, 'r', encoding='utf-8') as f:
                metadata = json.loads(await f.read())
            registered = True
            return await self._register_item(user_id, f"{user_id}_{timestamp}", metadata, kind, target_json_path,
                                             True, vector_db_service, broadcast_callback, parent_id, track)
        except Exception as e:
            log_service.error(f"Failed to process {kind} upload: {e}")
            if not registered:
                await asyncio.to_thread(self._remove_files, [target_mp3_path, target_json_path])
            return None

    async def create_text_item(self, user_id: int, kind: str, text: str, user_data: Dict, enhancement_service,
                               ai_service, vector_db_service=None, broadcast_callback: Optional[Callable] = None,
                               parent_id: Optional[str] = None, track: Optional[Dict] = None) -> Optional[Dict]:
        text = (text or "").strip()
        if not text:
            return None
        if kind == KIND_REPLY and self.parent_problem(parent_id):
            log_service.error(f"Reply refused for {parent_id}: {self.parent_problem(parent_id)}")
            return None
        try:
            processed = await enhancement_service.filter_text(
                text, kind, ai_service, context=self._llm_context(kind, parent_id, track),
                location=coarse_location(user_data.get("location"))
            )
            filtered_text = (processed.get("full_transcription") or "").strip() if processed else ""
            metadata_in = dict((processed or {}).get("transcription_metadata") or {})
            metadata_in.pop("sting_quote", None)
            metadata_in["total_words"] = len((filtered_text or text).split())
            metadata_in["duration"] = 0
            where = await self._where(metadata_in, user_data)
            if where:
                metadata_in["where"] = where
            metadata = {
                "full_transcription": filtered_text or text,
                "transcription_metadata": metadata_in,
                "word_level_transcription": [],
                "user_data": user_data,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "text_only": True,
                "transcript_filtered": bool(filtered_text),
            }
            stamp = self._new_stamp(user_id)
            json_path = settings.get_user_shoutouts_dir(user_id) / f"{stamp}.json"
            return await self._register_item(user_id, f"{user_id}_{stamp}", metadata, kind, json_path, False,
                                             vector_db_service, broadcast_callback, parent_id, track)
        except Exception as e:
            log_service.error(f"Failed to save typed {kind}: {e}")
            return None

    @staticmethod
    async def _where(metadata: Dict, user_data: Dict) -> Optional[Dict]:
        from services.user_content_speech_enhancement_service import shoutout_where
        try:
            where = await shoutout_where(metadata, user_data)
            return where.as_dict() if where is not None else None
        except Exception:
            return None

    async def _register_item(self, user_id: int, item_id: str, metadata: Dict, kind: str, json_path: Path,
                             has_audio: bool, vector_db_service, broadcast_callback, parent_id, track) -> Dict:
        metadata['id'] = item_id
        metadata['content_type'] = kind
        if parent_id:
            metadata['parent_id'] = parent_id
        if track:
            metadata['track'] = {k: track.get(k) for k in ("id", "title", "artist", "genre") if track.get(k)}

        async with aiofiles.open(json_path, 'w', encoding='utf-8') as f:
            await f.write(json.dumps(metadata, indent=2, ensure_ascii=False))

        await asyncio.to_thread(self._upsert_shoutout_to_db, item_id, user_id, metadata, has_audio, parent_id)
        self.remember_shoutout(item_id, metadata)

        if vector_db_service:
            try:
                await asyncio.to_thread(vector_db_service.add_meta, item_id, metadata)
            except Exception as e:
                vector_db_service.dirty = True
                log_service.warning(f"{kind} {item_id} saved but not searchable yet (background rebuild will add it): {e}")

        if broadcast_callback:
            await broadcast_callback(kind, item_id, public_shoutout(metadata))

        log_service.user_content(f"✅ {kind.capitalize()} {item_id} saved ({'voice' if has_audio else 'typed'})")
        return metadata

    def _get_all_shoutout_ids_from_db(self) -> List[str]:
        conn = self._get_connection()
        c = conn.cursor()
        c.execute("SELECT content_id FROM shoutouts")
        ids = [row[0] for row in c.fetchall()]
        conn.close()
        return ids

    def _bulk_delete_shoutouts(self, shoutout_ids: List[str]):
        conn = self._get_connection()
        c = conn.cursor()
        c.executemany("DELETE FROM shoutouts WHERE content_id = %s", [(sid,) for sid in shoutout_ids])
        conn.commit()
        conn.close()

    def _upsert_shoutout_to_db(self, shoutout_id: str, user_id: int, metadata: Dict, has_mp3: bool,
                                parent_id: Optional[str] = None) -> bool:
        conn = self._get_connection()
        c = conn.cursor()
        c.execute("SELECT content_id FROM shoutouts WHERE content_id = %s", (shoutout_id,))
        exists = c.fetchone() is not None

        transcription = metadata.get("full_transcription", "")
        meta_info = metadata.get("transcription_metadata", {}) or {}
        user_info = metadata.get("user_data", {}) or {}

        category = meta_info.get("category", "general")
        duration = meta_info.get("duration", 0.0)
        username = user_info.get("username", "Unknown")
        location = user_info.get("location", "")
        created_at = metadata.get("timestamp", datetime.now().isoformat())

        if parent_id is None:
            parent_id = metadata.get("parent_id")
        kind = kind_of(metadata)
        track_id = (metadata.get("track") or {}).get("id")

        if exists:
            c.execute('''UPDATE shoutouts
                         SET user_id=%s,
                             metadata_json=%s,
                             created_at=%s,
                             transcription=%s,
                             category=%s,
                             duration=%s,
                             username=%s,
                             location=%s,
                             has_mp3=%s,
                             parent_id=%s,
                             kind=%s,
                             track_id=%s
                         WHERE content_id = %s''',
                      (user_id, json.dumps(metadata), created_at, transcription, category,
                       duration, username, location, int(has_mp3), parent_id, kind, track_id, shoutout_id))
        else:
            c.execute('''INSERT INTO shoutouts (user_id, metadata_json, created_at, transcription, category,
                                                duration, username, location, has_mp3, parent_id, kind,
                                                track_id, content_id)
                         VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''',
                      (user_id, json.dumps(metadata), created_at, transcription, category,
                       duration, username, location, int(has_mp3), parent_id, kind, track_id, shoutout_id))

            if parent_id:
                c.execute("UPDATE shoutouts SET reply_count = reply_count + 1 WHERE content_id = %s", (parent_id,))

        conn.commit()
        conn.close()
        return not exists

    def get_shoutout(self, shoutout_id: str) -> Optional[Dict]:
        return self.shoutouts.get(shoutout_id)

    def get_enriched_shoutouts(self, shoutout_ids: List[str]) -> List[Optional[Dict]]:
        return [self.get_enriched_shoutout(sid) for sid in shoutout_ids]

    def get_enriched_shoutout(self, shoutout_id: str) -> Optional[Dict]:
        shoutout_data = self.shoutouts.get(shoutout_id)
        if not shoutout_data:
            return None

        try:
            uid, timestamp = shoutout_id.split('_', 1)
        except ValueError:
            return None

        enriched = shoutout_data.copy()
        enriched['id'] = shoutout_id
        enriched['kind'] = kind_of(shoutout_data)
        enriched['has_audio'] = not shoutout_data.get('text_only')
        enriched['audio_url'] = f"/api/user_content/shoutouts/audio/{uid}/{timestamp}.mp3" if enriched['has_audio'] else None
        sting = shoutout_data.get('sting') or {}
        enriched['sting_url'] = f"/api/user_content/shoutouts/audio/{uid}/{sting['file']}" if sting.get('file') else None

        if 'full_transcription' in enriched and 'transcription' not in enriched:
            enriched['transcription'] = enriched['full_transcription']
        if 'user_data' in enriched and 'user_id' not in enriched:
            enriched['user_id'] = enriched['user_data'].get('user_id')

        enriched['reply_count'] = len(self.children.get(shoutout_id, ()))
        enriched['parent_id'] = shoutout_data.get('parent_id')
        enriched['is_reply'] = enriched['parent_id'] is not None
        parent = self.shoutouts.get(enriched['parent_id']) if enriched['parent_id'] else None
        if parent:
            enriched['parent_preview'] = {
                'id': enriched['parent_id'],
                'username': (parent.get('user_data') or {}).get('username'),
                'transcription': (parent.get('full_transcription') or '')[:200],
            }
        return enriched

    async def enrich_shoutout_results(self, results: List[Dict], db_session=None) -> List[Dict]:
        user_ids = list(set(
            int(r.get('user_data', {}).get('user_id', 0)) for r in results if r.get('user_data', {}).get('user_id')))

        if not user_ids or not db_session:
            return results

        try:
            result = await db_session.execute(select(User).where(User.id.in_(user_ids)))
            users_map = {u.id: u for u in result.scalars().all()}

            for r in results:
                try:
                    uid = int(r.get('user_data', {}).get('user_id', 0))
                    if uid in users_map:
                        r['profile_picture'] = users_map[uid].profile_picture
                        if hasattr(users_map[uid], 'username'):
                            if 'user_data' not in r:
                                r['user_data'] = {}
                            r['user_data']['username'] = users_map[uid].username
                            r['username'] = users_map[uid].username

                    if 'user_data' in r:
                        r['user_id'] = r['user_data'].get('user_id')
                except (ValueError, TypeError):
                    pass
            return results
        except Exception as e:
            log_service.error(f"Error enriching shoutouts: {e}")
            return results

    def delete_shoutout(self, shoutout_id: str, cascade_replies: bool = True) -> bool:
        if shoutout_id not in self.shoutouts:
            return False

        try:
            conn = self._get_connection()
            try:
                c = conn.cursor()

                c.execute("SELECT parent_id FROM shoutouts WHERE content_id = %s", (shoutout_id,))
                row = c.fetchone()
                parent_id = row[0] if row else None

                reply_ids = []
                if cascade_replies:
                    c.execute("SELECT content_id FROM shoutouts WHERE parent_id = %s", (shoutout_id,))
                    reply_ids = [r[0] for r in c.fetchall()]
            finally:
                conn.close()

            for reply_id in reply_ids:
                self._delete_shoutout_files_and_memory(reply_id)

            self._delete_shoutout_files_and_memory(shoutout_id)

            conn = self._get_connection()
            try:
                c = conn.cursor()

                if reply_ids:
                    c.execute("DELETE FROM shoutouts WHERE content_id = ANY(%s)", (reply_ids,))
                    log_service.user_content(f"Cascade deleted {len(reply_ids)} replies for shoutout {shoutout_id}")

                c.execute("DELETE FROM shoutouts WHERE content_id = %s", (shoutout_id,))

                if parent_id:
                    c.execute("UPDATE shoutouts SET reply_count = GREATEST(0, reply_count - 1) WHERE content_id = %s", (parent_id,))

                conn.commit()
            finally:
                conn.close()

            return True
        except Exception as e:
            log_service.error(f"Failed to delete shoutout {shoutout_id}: {e}")
            return False

    def _delete_shoutout_files_and_memory(self, shoutout_id: str):
        try:
            uid, timestamp = shoutout_id.split('_', 1)
            user_dir = settings.get_user_shoutouts_dir(int(uid))
            mp3_path = user_dir / f"{timestamp}.mp3"
            self._remove_files([user_dir / f"{timestamp}.json", mp3_path, Path(sting_file(mp3_path))])
            self.forget_shoutout(shoutout_id)
        except Exception as e:
            log_service.error(f"Error deleting files for {shoutout_id}: {e}")

    def get_stats(self, category: Optional[str] = None) -> Dict:
        total = 0
        duration = 0.0
        categories = {}
        for t in self.shoutouts.values():
            if kind_of(t) != KIND_SHOUTOUT:
                continue
            shoutout_category = t.get("transcription_metadata", {}).get("category", "unknown")
            if category and shoutout_category.lower() != category.lower():
                continue
            total += 1
            dur = t.get("transcription_metadata", {}).get("duration", 0)
            if dur:
                duration += float(dur)
            if shoutout_category:
                categories[shoutout_category] = categories.get(shoutout_category, 0) + 1
        return {
            "total_shoutouts": total,
            "total_duration_ms": int(duration * 1000),
            "total_duration_formatted": self._format_duration(int(duration * 1000)),
            "category_counts": categories
        }

    def _format_duration(self, ms: int) -> str:
        m, s = divmod(ms // 1000, 60)
        h, m = divmod(m, 60)
        return f"{h}h {m}m" if h else f"{m}m {s}s"

    def get_replies(self, parent_id: str) -> List[Dict]:
        replies = [self.get_enriched_shoutout(rid) for rid in self.children.get(parent_id, ())]
        replies = [r for r in replies if r]
        replies.sort(key=lambda r: r.get('timestamp', ''), reverse=True)
        return replies

    def items_by_user(self, user_id: int) -> Dict[str, List[Dict]]:
        mine: Dict[str, List[Dict]] = {KIND_SHOUTOUT: [], KIND_REPLY: [], KIND_REVIEW: []}
        prefix = f"{user_id}_"
        for sid in self.shoutout_ids:
            if sid.startswith(prefix):
                enriched = self.get_enriched_shoutout(sid)
                if enriched:
                    mine[enriched['kind']].append(enriched)
        return mine

    def reviews_for_track(self, track_id: str, with_audio: bool = False) -> List[Dict]:
        reviews = []
        for sid in self.shoutout_ids:
            data = self.shoutouts.get(sid) or {}
            if kind_of(data) != KIND_REVIEW or str((data.get('track') or {}).get('id')) != str(track_id):
                continue
            if with_audio and data.get('text_only'):
                continue
            enriched = self.get_enriched_shoutout(sid)
            if enriched:
                reviews.append(enriched)
        return reviews

    def is_root_shoutout(self, shoutout_id: str) -> bool:
        return self.parent_problem(shoutout_id) is None
